//loaders
export const ENABLE_LOADER = 'ENABLE_LOADER';
export const DISABLE_LOADER = 'DISABLE_LOADER';


//intro
export const IS_NEW_USER = 'IS_NEW_USER';
export const START_APP = 'START_APP';
export const IS_HEALTH_SCREEN_OPEN ='IS_HEALTH_SCREEN_OPEN';
export const IS_HEALTH_DOC_SCREEN_OPEN = 'IS_HEALTH_DOC_SCREEN_OPEN';
export const SHOW_MEDICAL_RECORD = 'SHOW_MEDICAL_RECORD';
export const IS_HOME_PAGE_TOUR_DONE = 'IS_HOME_PAGE_TOUR_DONE';


// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_LOADING_ENDED = 'LOGIN_LOADING_ENDED';
export const LOGIN_FAILED_TOAST = 'LOGIN_FAILED_TOAST';
export const LOGIN_RESET = 'LOGIN_RESET';

export const AUTH_RESPONSE = 'AUTH_RESPONSE';
export const AUTH_RESET = 'AUTH_RESET';
export const INVALID_TOKEN = 'INVALID_TOKEN';


// Logout
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_RESPONSE = 'LOGOUT_RESPONSE';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

// REGISTER
export const PROFILE_TYPES = 'PROFILE_TYPES';
export const SET_PROFILE_TYPES = 'SET_PROFILE_TYPES';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const SEND_OTP_REQUEST = 'SEND_OTP_REQUEST';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const REGISTER_RESPONSE = 'REGISTER_RESPONSE';
export const REGISTER_LOADING_ENDED = 'LOGIN_LOADING_ENDED';
export const OPEN_OTP_MODAL = 'OPEN_OTP_MODAL';


//HOME
export const VIDEO_REQUEST = 'VIDEO_REQUEST';
export const BLOG_REQUEST = 'BLOG_REQUEST';
export const SET_VIDEO_LIST = 'SET_VIDEO_LIST';
export const SET_BLOG_LIST = 'SET_BLOG_LIST';
export const GET_USER_LOGIN_STATUS ='GET_USER_LOGIN_STATUS';
export const ADD_FEELING_REQUEST = 'ADD_FEELING_REQUEST';
export const ADD_FEELING_FAILED = 'ADD_FEELING_FAILED';
export const ADD_FEELING_RESPONSE = 'ADD_FEELING_RESPONSE';
export const ADD_FEELING_SUCCESS = 'ADD_FEELING_SUCCESS';

//Health Record
export const DISEASE_REQUEST = 'DISEASE_REQUEST';
export const SET_DISEASE_LIST = 'SET_DISEASE_LIST';
export const ADD_NEW_DISEASE_REQUEST = 'ADD_NEW_DISEASE';
export const ADD_NEW_DISEASE_FAILED = 'ADD_NEW_DISEASE_FAILED';
export const ADD_NEW_DISEASE_RESPONSE = 'ADD_NEW_DISEASE_RESPONSE';

//Blogs
export const BLOG_DETAIL_REQUEST = 'BLOG_DETAIL_REQUEST';
export const SET_BLOG_DETAIL = 'SET_BLOG_DETAIL';

//Pill Reminder
export const PILL_REMINDER_REQUEST = 'PILL_REMINDER_REQUEST';
export const PILL_REMINDER_LIST = 'PILL_REMINDER_LIST';
export const PILL_MEDICINE_LIST = 'PILL_MEDICINE_LIST';
export const MEDICINE_TYPE = 'MEDICINE_TYPE';
export const ADD_PILL_REMINDER_REQUEST = 'ADD_PILL_REMINDER_REQUEST';

export const GET_PILL_REMINDER_REQUEST ='GET_PILL_REMINDER_REQUEST'
export const SET_PILL_REMINDER = 'SET_PILL_REMINDER';
export const UPDATE_PILL_REMINDER_REQUEST = 'UPDATE_PILL_REMINDER_REQUEST';
export const UPDATE_PILL_REMINDER_FAILED = 'UPDATE_PILL_REMINDER_FAILED';
export const UPDATE_PILL_REMINDER_RESPONSE = 'UPDATE_PILL_REMINDER_RESPONSE';

//Doctor Appointment
export const DISEASE_LIST_REQUEST = 'DISEASE_LIST_REQUEST';
export const SET_DISEASES_LIST = 'SET_DISEASES_LIST';
export const ADD_DOCTOR_APPOINTMENT_REQUEST = 'ADD_DOCTOR_APPOINTMENT_REQUEST';
export const ADD_DOCTOR_APPOINTMENT_FAILED = 'ADD_DOCTOR_APPOINTMENT_FAILED';
export const ADD_DOCTOR_APPOINTMENT_RESPONSE = 'ADD_DOCTOR_APPOINTMENT_RESPONSE';
export const ADD_DOCTOR_APPOINTMENT_SUCCESS = 'ADD_DOCTOR_APPOINTMENT_SUCCESS';

export const GET_DOCTOR_APPOINTMENT_REQUEST = 'GET_DOCTOR_APPOINTMENT_REQUEST';
export const SET_DOCTOR_APPOINTMENT = 'SET_DOCTOR_APPOINTMENT';
export const UPDATE_DOCTOR_APPOINTMENT_REQUEST = 'UPDATE_DOCTOR_APPOINTMENT_REQUEST';
export const UPDATE_DOCTOR_APPOINTMENT_FAILED = 'UPDATE_DOCTOR_APPOINTMENT_FAILED';
export const UPDATE_DOCTOR_APPOINTMENT_RESPONSE = 'UPDATE_DOCTOR_APPOINTMENT_RESPONSE';

//Profile
export const UPDATE_PROFILE_PIC = 'UPDATE_PROFILE_PIC';
export const UPDATE_PROFILE_RESPONSE = 'UPDATE_PROFILE_RESPONSE';
export const UPDATE_PROFILE_IMAGE = 'UPDATE_PROFILE_IMAGE';
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED';
export const CHANGE_SEND_ME_ALERT = 'CHANGE_SEND_ME_ALERT';
export const CHANGE_EMAIL_ENABLE = 'CHANGE_EMAIL_ENABLE';
export const UPDATE_NOTIFICATION_ENABLE = 'UPDATE_NOTIFICATION_ENABLE';
export const UPDATE_EMAIL_ENABLE = 'UPDATE_EMAIL_ENABLE';
export const CHANGE_INSURANCE_CLAIM = 'CHANGE_INSURANCE_CLAIM';
export const CHANGE_MEDICAL_EXPENSE = 'CHANGE_MEDICAL_EXPENSE';
export const CHANGE_PRESCRIPTION = 'CHANGE_PRESCRIPTION';
export const CHANGE_TEST_RESULT = 'CHANGE_TEST_RESULT';
export const CHANGE_HOSPITAL_DISCHARGE_PAPERS = 'CHANGE_HOSPITAL_DISCHARGE_PAPERS';
export const CHANGE_RADIOLOGY_AND_IMAGING = 'CHANGE_RADIOLOGY_AND_IMAGING';
export const CHANGE_CLINICAL_PHOTOGRAPH = 'CHANGE_CLINICAL_PHOTOGRAPH';
export const CHANGE_GENETIC_TESTS = 'CHANGE_GENETIC_TESTS';
export const CHANGE_LABORATORY_TESTS = 'CHANGE_LABORATORY_TESTS'

//KYC Verificaiton
export const ADD_KYC_VERIFICTION = 'ADD_KYC_VERIFICTION';

//Disease
export const LIST_USER_DISEASE_DOC = 'LIST_USER_DISEASE_DOC';
export const SET_USER_DISEASE_DOC = 'SET_USER_DISEASE_DOC';

//Wallet
export const WALLET_TRANSACTION_HISTORY_REQUEST = 'WALLET_TRANSACTION_HISTORY_REQUEST';
export const SET_WALLET_TRANSACTION_HISTORY = 'SET_WALLET_TRANSACTION_HISTORY';
export const SET_WALLET_BALANCE = 'SET_WALLET_BALANCE';
export const REQUEST_WALLET = 'REQUEST_WALLET';
export const SET_REEDEM_POINT = 'SET_REEDEM_POINT';
export const REQUEST_CONTENT='REQUEST_CONTENT';
export const SET_CONTENT='SET_CONTENT';

// Notification
export const NOTIFICATION_REQUEST = 'NOTIFICATION_REQUEST';
export const NOTIFICATION_RESPONSE = 'NOTIFICATION_RESPONSE';
export const NOTIFICATION_FAILED = 'NOTIFICATION_FAILED';
export const NOTIFICATION_SUCCESS = 'NOTIFICATION_LOADING_SUCCESS';
