/* App config for images
 */
const images = {
  icons: {
    logo: require('../assets/images/logo.png'),
    upload_image: require('../assets/images/upload-image.png'),
    success: require('../assets/images/success.png'),
  },
  intro: {
    first: require('app/assets/images/intro/first.png'),
    second: require('app/assets/images/intro/second.png'),
    third: require('app/assets/images/intro/third.png'),
    fourth: require('app/assets/images/intro/fourth.png'),
    bg: require('app/assets/images/button-rectangleBG.png'),
  },
  login: {
    show: require('../assets/images/view-eye.png'),
    hide: require('../assets/images/hide-eye.png'),
    background: require('../assets/images/background.png'),
    left_arrow: require('../assets/images/left-arrow.png'),
    rd_rectangle: require('../assets/images/rounded-rectangle.png'),
  },
  forgotPassword: {
    show: require('../assets/images/view-eye.png'),
    hide: require('../assets/images/hide-eye.png'),
    background: require('../assets/images/background.png'),
    left_arrow: require('../assets/images/left-arrow.png'),
    rd_rectangle: require('../assets/images/rounded-rectangle.png'),
  },
  videoSignInOut: {
    fourth: require('../assets/images/intro/fourth.png'),
    logo: require('../assets/images/kyt-logo.png'),
  },
  register: {
    rd_rectangle: require('../assets/images/rounded-rectangle.png'),
    background: require('../assets/images/background.png'),
    left_arrow: require('../assets/images/left-arrow.png'),
    down_arrow: require('../assets/images/down-arrow-black.png'),
    checked: require('../assets/images/checked.png'),
    un_checked: require('../assets/images/unchecked.png'),
  },
  timeline: {
    roundBG: require('../assets/images/roundBG.png'),
    doctor: require('../assets/images/doctor.png'),
    image1: require('../assets/images/image1.png'),
    image2: require('../assets/images/image2.png'),
    down_arrow: require('../assets/images/down-arrow-black.png'),
    left_arrow: require('../assets/images/left-arrow.png'),
    background: require('../assets/images/background.png'),
    filter: require('../assets/images/filter.png'),
    feeling: require('../assets/images/feeling.png'),
  },
  footerTab: {
    homeSelected: require('../assets/images/tabs/homeSelected.png'),
    home: require('../assets/images/tabs/home.png'),
    heartSelected: require('../assets/images/tabs/heartSelected.png'),
    heart: require('../assets/images/tabs/heart.png'),
    bar_chartSelected: require('../assets/images/tabs/bar-chartSelected.png'),
    bar_chart: require('../assets/images/tabs/bar-chart.png'),
    notification: require('../assets/images/tabs/notification.png'),
    white_notification: require('../assets/images/tabs/white_notification.png'),
    reminderSelected: require('../assets/images/tabs/reminderSelected.png'),
    reminder: require('../assets/images/tabs/reminder.png'),
    walletSelected: require('../assets/images/tabs/walletSelected.png'),
    wallet: require('../assets/images/tabs/wallet.png'),
  },
  home: {
    GeneticTests: require('../assets/images/floating/icons/Genetic-tests.png'),
    HospitalDischarge: require('../assets/images/floating/icons/Hospital-discharge.png'),
    LaboratoryTests: require('../assets/images/floating/icons/Laboratory-tests.png'),
    MedicalExpenses: require('../assets/images/floating/icons/Medical-expenses.png'),
    Prescription: require('../assets/images/floating/icons/Prescription.png'),
    RadiologyImaging: require('../assets/images/floating/icons/Radiology-imaging.png'),
    InsuranceClaims: require('../assets/images/floating/icons/Insurance-claims.png'),
    ClinicalPresentation: require('../assets/images/floating/icons/Clinical-Presentation.png'),
    insuranceBG: require('../assets/images/floating/insuranceBG.png'),
    insurance: require('../assets/images/floating/insurance.png'),
    medicalBG: require('../assets/images/floating/medicalBG.png'),
    medical: require('../assets/images/floating/medical.png'),
    doctorBG: require('../assets/images/floating/doctorBG.png'),
    doctor: require('../assets/images/floating/doctor.png'),
    prescriptionBG: require('../assets/images/floating/prescriptionBG.png'),
    prescription: require('../assets/images/floating/prescription.png'),
    result: require('../assets/images/floating/result.png'),
    resultBG: require('../assets/images/floating/resultBG.png'),
    profile: require('../assets/images/user.png'),
    medication: require('../assets/images/medication.png'),
    doctorIcon: require('../assets/images/doctor.png'),
    shareWhite: require('../assets/images/share_white.png'),
    layer: require('../assets/images/Layer.png'),
    share: require('../assets/images/share.png'),
    cross_icon: require('../assets/images/floating/cross-icon.png'),
    plus_icon: require('../assets/images/floating/plus-icon.png'),
    more: require('../assets/images/more.png'),
    rounded_rectangle: require('../assets/images/rounded-rectangle.png'),
    button_rectangleBG: require('../assets/images/button-rectangleBG.png'),
    edit: require('../assets/images/edit.png'),
    roundBG: require('../assets/images/roundBG.png'),
    videoContain: require('../assets/images/videoContain.png'),
    smiley: require('../assets/images/floating/icons/feeling-today.png'),
    feelingBG:require('../assets/images/floating/icons/feelingBG.png'),
  },
  wallet: {
    background: require('../assets/images/wallet/headerBG.png'),
    trophy: require('../assets/images/wallet/trophy.png'),
    wallet: require('../assets/images/wallet/wallet.png'),
    info: require('../assets/images/wallet/info.png'),
    button_rectangleBG: require('../assets/images/button-rectangleBG.png'),
  },
  health: {
    disease_symbol: require('../assets/images/health/disease-symbol.png'),
    infectious: require('../assets/images/health/infectious.png'),
    allergies: require('../assets/images/health/allergies.png'),
    cancer: require('../assets/images/health/cancer.png'),
    celiac_dis: require('../assets/images/health/celiac_dis.png'),
    white: require('../assets/images/health/white.png'),
    add: require('../assets/images/health/add.png'),
    crohns_colitis: require('../assets/images/health/crohns_colitis.png'),
    background: require('../assets/images/background.png'),
    left_arrow: require('../assets/images/left-arrow.png'),
    healthInsurance: require('../assets/images/healthInsurance.png'),
  },
  doctorAppoint: {
    background: require('../assets/images/background.png'),
    left_arrow: require('../assets/images/left-arrow.png'),
    appointment: require('../assets/images/appointment.png'),
    rd_rectangle: require('../assets/images/rounded-rectangle.png'),
  },
  pillReminder: {
    rd_rectangle: require('../assets/images/rounded-rectangle.png'),
    down_arrow: require('../assets/images/down-arrow-black.png'),
    edit: require('../assets/images/edit.png'),
    reminder: require('../assets/images/reminder.png'),
    add: require('../assets/images/plus.png'),
    left_arrow: require('../assets/images/left-arrow.png'),
    skip: require('../assets/images/skip.png'),
    take: require('../assets/images/take.png'),
    reschedule: require('../assets/images/reschedule.png'),
    capsule: require('../assets/images/pillsIcon/capsule.png'),
    cream_ointment: require('../assets/images/pillsIcon/cream_ointment.png'),
    drops: require('../assets/images/pillsIcon/drops.png'),
    lozenges: require('../assets/images/pillsIcon/lozenges.png'),
    spray: require('../assets/images/pillsIcon/spray.png'),
    syrup: require('../assets/images/pillsIcon/syrup.png'),
    tablet: require('../assets/images/pillsIcon/tablet.png'),
    delete: require('../assets/images/delete.png'),
    plus: require('../assets/images/plus.png'),
  },
  profile: {
    background: require('../assets/images/background.png'),
    profile: require('../assets/images/user.png'),
    setting_black: require('../assets/images/setting_black.png'),
    share_black: require('../assets/images/share_black.png'),
    share: require('../assets/images/share.png'),
    arrow_right_black: require('../assets/images/arrow_right_black.png'),
    logout_black: require('../assets/images/logout_black.png'),
    rectangle_transparent_bg: require('../assets/images/rectangle_transparent_bg.png'),
    edit: require('../assets/images/edit.png'),
    white_bg: require('../assets/images/white_bg.png'),
    change_password: require('../assets/images/change_password.png'),
    healthInsurance: require('../assets/images/profile/insurance.png'),
    adharCard: require('../assets/images/profile/adharCard.png'),
    panCard: require('../assets/images/profile/panCard.png'),
    panCardUpload: require('../assets/images/profile/panCardUpload.png'),
    leftBottom: require('../assets/images/profile/leftBottom.png'),
    rightBottom: require('../assets/images/profile/rightBottom.png'),
    leftTop: require('../assets/images/profile/leftTop.png'),
    rightTop: require('../assets/images/profile/rightTop.png'),
  },
  disease: {
    // insuranceBG: require('app/assets/images/floating/insuranceBG.png'),
    // insurance: require('app/assets/images/floating/insurance.png'),
    // medicalBG: require('app/assets/images/floating/medicalBG.png'),
    // medical: require('app/assets/images/floating/medical.png'),
    // doctorBG: require('app/assets/images/floating/doctorBG.png'),
    // doctor: require('app/assets/images/floating/doctor.png'),
    // prescriptionBG: require('../assets/images/floating/prescriptionBG.png'),
    // prescription: require('../assets/images/floating/prescription.png'),
    // result: require('../assets/images/floating/result.png'),
    // resultBG: require('../assets/images/floating/resultBG.png'),
    health_1: require('../assets/images/health/1.png'),
    health_2: require('../assets/images/health/2.png'),
    health_3: require('../assets/images/health/3.png'),
    health_4: require('../assets/images/health/4.png'),
    health_5: require('../assets/images/health/5.png'),
    health_6: require('../assets/images/health/6.png'),
    mail: require('../assets/images/mail.png'),
    email: require('../assets/images/email.png'),
    pdf: require('../assets/images/pdf.png'),
    share: require('../assets/images/share.png'),
    cross_icon: require('../assets/images/floating/cross-icon.png'),
    plus_icon: require('../assets/images/floating/plus-icon.png'),
    plus: require('../assets/images/floating/plus.png'),
    more: require('../assets/images/more.png'),
    background: require('../assets/images/background.png'),
    left_arrow: require('../assets/images/left-arrow.png'),
    delete: require('../assets/images/delete.png'),
    close: require('../assets/images/close.png'),
    info: require('../assets/images/info.png'),
    edit: require('../assets/images/edit.png'),
  },
  rxTimeline: {
    pencil: require('../assets/images/pencil.png'),
    trash_can: require('../assets/images/trash-can.png'),
  },
  feeling: {
    feel_1: require('../assets/images/smiley/test/mad2.png'),
    feel_2: require('../assets/images/smiley/test/sad2.png'),
    feel_3: require('../assets/images/smiley/test/confused2.png'),
    feel_4: require('../assets/images/smiley/test/happy4.png'),
    feel_5: require('../assets/images/smiley/test/happy2.png'),
  },
};

export default images;
